/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/TabBar`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/CompanyMap`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/PlaceDetail`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/Places`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/QRCodeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/TabBar`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/CompanyMap`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/PlaceDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/Places`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/QRCodeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/context/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/../components/ui/TabBar${`?${string}` | `#${string}` | ''}` | `/../src/screens/CompanyMap${`?${string}` | `#${string}` | ''}` | `/../src/screens/PlaceDetail${`?${string}` | `#${string}` | ''}` | `/../src/screens/Places${`?${string}` | `#${string}` | ''}` | `/../src/screens/QRCodeScreen${`?${string}` | `#${string}` | ''}` | `/../src/context/AuthContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/TabBar`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/CompanyMap`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/PlaceDetail`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/Places`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/QRCodeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/context/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
